"""
UCI 命令执行器 — 封装 OpenWrt UCI 命令行操作。
支持 dry_run 模式，便于开发调试和审计。
"""

from __future__ import annotations

import subprocess


class UciExecutor:
    """
    对 `uci` CLI 的面向对象封装。

    所有 UCI 操作通过本类执行，好处：
    - 集中管理错误处理
    - dry_run 模式只打印命令，不实际执行
    - 方便以后替换为 libuci 绑定或 REST API
    """

    def __init__(self, dry_run: bool = False, export: bool = False) -> None:
        self._dry_run = dry_run
        self._export = export
        self._commands: list[str] = []

    # ----------------------------------------------------------
    # 底层执行
    # ----------------------------------------------------------
    def run(self, command: str) -> None:
        """执行任意 uci 命令"""
        full_cmd = f"uci {command}"

        # Export 模式：仅收集命令，不执行
        if self._export:
            self._commands.append(full_cmd)
            return

        # Dry-run 模式：仅打印
        if self._dry_run:
            print(f"  [DRY-RUN] {full_cmd}")
            return

        subprocess.run(full_cmd, shell=True, check=True)

    # ----------------------------------------------------------
    # 查询 API
    # ----------------------------------------------------------
    def query(self, command: str) -> str | None:
        """执行 uci 命令并返回输出，dry-run/export 时返回 None"""
        if self._dry_run or self._export:
            return None
        result = subprocess.run(
            f"uci {command}", shell=True, capture_output=True, text=True,
        )
        return result.stdout.strip() if result.returncode == 0 else None

    @property
    def is_dry_run(self) -> bool:
        return self._dry_run

    @property
    def is_export(self) -> bool:
        return self._export

    # ----------------------------------------------------------
    # 导出 API
    # ----------------------------------------------------------
    def write_script(self, path: str) -> None:
        """将收集的命令写入 Shell 脚本文件"""
        if not self._export:
            raise RuntimeError("当前非 export 模式，无法写入脚本")

        import datetime

        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        content = [
            "#!/bin/sh",
            f"# Generated by Auto VLAN at {now}",
            "# ⚠️ 此脚本由程序自动生成，请勿手动编辑",
            "",
            "set -e",  # 遇到错误立即退出
            "",
            "# --- UCI 配置开始 ---",
        ]
        content.extend(self._commands)
        content.extend(
            [
                "",
                "# --- 重启服务 ---",
                "/etc/init.d/network restart",
                'echo "✅ 部署完成"',
                "",
            ]
        )

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(content))
        
        print(f"\n✨ 部署脚本已导出至: {path}")

    # ----------------------------------------------------------
    # 语义化 API
    # ----------------------------------------------------------
    def set(self, path: str, value: str) -> None:
        """uci set <path>=<value>"""
        self.run(f"set {path}='{value}'")

    def add(self, config: str, section_type: str) -> None:
        """uci add <config> <type>  (匿名 section)"""
        self.run(f"add {config} {section_type}")

    def add_list(self, path: str, value: str) -> None:
        """uci add_list <path>=<value>"""
        self.run(f"add_list {path}='{value}'")

    def delete(self, path: str) -> None:
        """uci delete <path>"""
        self.run(f"delete {path}")

    def commit(self, config: str) -> None:
        """uci commit <config>"""
        self.run(f"commit {config}")
